# Generated by Django 4.0.4 on 2023-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='nome_equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='participantes',
            field=models.CharField(max_length=200, null=True, verbose_name='Participantes'),
        ),
    ]
