# Generated by Django 4.0.4 on 2023-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipe', '0002_remove_equipe_nome_equipe_equipe_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='Campeonatos',
            field=models.CharField(max_length=200, null=True, verbose_name='Campeonatos'),
        ),
    ]
