# Generated by Django 4.0.4 on 2023-05-02 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campeonato', '0002_alter_campeonato_qtdequipe_and_more'),
        ('Equipe', '0003_equipe_campeonatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='Campeonatos',
        ),
        migrations.AddField(
            model_name='equipe',
            name='Campeonato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Campeonato.campeonato'),
        ),
    ]
