# Generated by Django 4.0.4 on 2023-07-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipe', '0004_remove_equipe_campeonatos_equipe_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='escudo',
            field=models.ImageField(null=True, upload_to='static/img/escudos'),
        ),
    ]
