# Generated by Django 4.0.4 on 2023-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='qtdequipe',
            field=models.IntegerField(null=True, verbose_name='Quantidade de equipes'),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='tipopartida',
            field=models.CharField(max_length=200, null=True, verbose_name='Tipo de partida'),
        ),
    ]
