# Generated by Django 4.0.4 on 2023-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome da Partida'),
        ),
    ]
