# Generated by Django 4.0.4 on 2023-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0003_alter_partida_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='resultado',
            field=models.CharField(max_length=25, null=True, verbose_name='Resultado'),
        ),
    ]
