# Generated by Django 4.0.4 on 2023-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0004_alter_partida_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='horario',
            field=models.DateField(verbose_name='Horario'),
        ),
    ]
