# Generated by Django 4.0.4 on 2023-07-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0009_alter_partida_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='horario',
            field=models.DateField(blank=True, null=True, verbose_name='Horario'),
        ),
    ]
